apiVersion: v1
kind: Service
metadata:
  name: hub-svc
  labels:
    app: hub
spec:
  type: LoadBalancer
  selector:
    app: hub
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
      
